# Generated by Django 4.2.5 on 2024-01-09 07:24

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_captiopns_post_captions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(null=True, upload_to=posts.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
