# Generated by Django 5.0.3 on 2024-11-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
    ]
